"""
slack_message_builder.py
========================
Standalone module responsible for building Slack messages generated by the
Beecker monitoring agent.

Responsibilities:
    - Build formatted Slack messages (mrkdwn) depending on the execution scenario.
    - Remain completely transport-agnostic (no dependency on HTTP clients or Slack API).
    - Receive the normalized dictionary returned by BeeckerAPI together with bot metadata.
    - Return only the final message string ready to be sent.

Supported scenarios (invoked via build() and build_multi()):
    - HAPPY_PATH       → Execution completed without errors.
    - PARTIAL_FAILURE  → Execution completed with failed transactions.
    - CRITICAL_FAILURE → Execution failed completely (run_state = failed).
    - OVERTIME         → Bot execution exceeded the reference average runtime.

Separate method (does NOT go through build()):
    - build_initial()  → Execution start message (includes run_id if provided).

Example::

    from slack_message_builder import RPAMessageBuilder

    builder = RPAMessageBuilder()

    # Execution start notification
    init_msg = builder.build_initial(bot_id="AIN.002", bot_name="Order entry", run_id="165685")

    # Single execution status notification
    message = builder.build(
        status_dict=api_response,
        bot_id="AIN.002",
        bot_name="Order entry - Performer",
        transaction_unit="archivos",
        transaction_unit_singular="archivo",
        mention_user_ids=["U123ABC", "U456DEF"],
        freshdesk_url="https://...",
    )

    # Fused multi-execution status notification (bee_observa)
    message = builder.build_multi(
        bot_id="MME.001",
        bot_name="Gastos de viaje",
        status_list=[status_123, status_124],   # already sorted chronologically
        transaction_unit="Reportes",
        transaction_unit_singular="Reporte",
    )
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import List, Optional


class ExecutionScenario(Enum):
    """Enumeration of possible monitored RPA execution scenarios."""
    HAPPY_PATH       = auto()
    PARTIAL_FAILURE  = auto()
    CRITICAL_FAILURE = auto()
    OVERTIME         = auto()


class ScenarioResolver:
    """
    Resolve the execution scenario based on the normalized status dictionary.

    Resolution priority:
        OVERTIME > CRITICAL_FAILURE > PARTIAL_FAILURE > HAPPY_PATH

    OVERTIME takes precedence because it may coexist with any run_state.
    """

    def resolve(self, status: dict) -> ExecutionScenario:
        if not status:
            raise ValueError(
                "El dict de status está vacío. "
                "Para generar un mensaje de inicio usa build_initial() en lugar de build()."
            )

        self._validate(status)
        run_state: str = status["run_state"].lower()

        if run_state == "failed":
            return ExecutionScenario.CRITICAL_FAILURE

        if status.get("overtime_flag", False):
            return ExecutionScenario.OVERTIME

        if status.get("failed_transactions", 0) > 0:
            return ExecutionScenario.PARTIAL_FAILURE

        return ExecutionScenario.HAPPY_PATH

    @staticmethod
    def _validate(status: dict) -> None:
        required = {"run_id", "run_state"}
        missing  = required - status.keys()
        if missing:
            raise ValueError(
                f"El dict de status no contiene los campos requeridos: {missing}"
            )


class GreetingProvider:
    """Provides random greetings used at the beginning of Slack messages."""

    _GREETINGS: list[str] = [
        "¡Hola equipo!",
        "¡Buen día, equipo!",
        "¡Qué tal, equipo!",
        "¡Atención equipo!",
        "¡Hola a todos!",
    ]

    def get(self) -> str:
        """Return a randomly selected greeting."""
        return random.choice(self._GREETINGS)


@dataclass
class MessageContext:
    """
    Container with all information required to build a Slack message.

    Attributes:
        status:                    Normalized status dictionary returned by BeeckerAPI.
        bot_id:                    Bot identifier (e.g. 'AIN.002'). Displayed in uppercase.
        bot_name:                  Human-readable bot name.
        transaction_unit:          Transaction unit in plural form.
        transaction_unit_singular: Transaction unit in singular form.
        greeting:                  Greeting used at the start of the message.
        run_id:                    Optional execution identifier shown in the header.
        show_error_groups:         Whether grouped error details should be included.
        max_error_groups:          Maximum number of error groups to display.
        mention_user_ids:          Slack user IDs to mention.
        freshdesk_url:             FreshDesk ticket URL associated with the client.
    """
    status: dict
    bot_id: str
    bot_name: str
    transaction_unit: str
    transaction_unit_singular: str
    greeting: str
    run_id: Optional[str] = None
    show_error_groups: bool = True
    max_error_groups: Optional[int] = None
    mention_user_ids: List[str] = field(default_factory=list)
    freshdesk_url: Optional[str] = None


class _BaseMessageBuilder:
    """Base class providing helper utilities for Slack mrkdwn formatting."""

    def build(self, ctx: MessageContext) -> str:
        raise NotImplementedError

    _IN_PROGRESS_STATES = {"in progress", "pending"}

    _STATE_EMOJI: dict[str, str] = {
        "in progress": ":in_progress:",
        "pending":     ":in_progress:",
        "completed":   ":white_check_mark:",
        "failed":      ":warning-icon:",
    }

    @staticmethod
    def _bot_header(ctx: MessageContext) -> str:
        """
        Generate the message header containing the bot identifier and execution state.
        If ctx.run_id is set, includes the execution number: La ejecución #123 del bot...
        """
        run_state   = ctx.status.get("run_state", "").lower()
        in_progress = run_state in _BaseMessageBuilder._IN_PROGRESS_STATES
        verb        = "está en progreso" if in_progress else "ha finalizado"
        emoji       = _BaseMessageBuilder._STATE_EMOJI.get(run_state, "")
        emoji_str   = f" {emoji}" if emoji else ""

        run_id = ctx.status.get("run_id")
        run_id_tag = f" `#{run_id}`" if run_id else ""

        return (
            f"La ejecución{run_id_tag} del bot `{ctx.bot_id.upper()}` *→ {ctx.bot_name}* "
            f"{verb}{emoji_str} `{run_state.capitalize()}`"
        )

    @staticmethod
    def _timing_info(status: dict) -> str:
        """Generate the execution timing line including start, end and duration."""
        start = status.get("start_run", "N/A")

        if status.get("run_state") == "failed":
            return f"*Inicio:* {start}"

        elapsed = status.get("elapsed_minutes")
        elapsed_str = f" (duración: {elapsed:.1f} min)" if elapsed is not None else ""

        if status.get("run_state") in ["in progress", "pending"]:
            return f"*Inicio:* {start}  -  *En curso:* {elapsed_str}"

        end = status.get("end_run", "En curso")
        return f"*Inicio:* {start}  -  *Fin:* {end}{elapsed_str}"

    @staticmethod
    def _transaction_summary(
        status: dict, unit_plural: str, unit_singular: str
    ) -> list[str]:
        """Generate summary lines describing processed transactions."""
        total     = status.get("total_transactions", 0)
        completed = status.get("completed_transactions", 0)
        failed    = status.get("failed_transactions", 0)
        pending   = max(0, total - completed - failed)

        unit = unit_plural if total != 1 else unit_singular

        lines = [f"Se han procesado *{completed}* de *{total}* {unit}."]

        details = []
        if failed > 0:
            unit_f = unit_singular if failed == 1 else unit_plural
            details.append(f"*➤ {failed} {unit_f}* `failed` ")
        if pending > 0:
            unit_p = unit_singular if pending == 1 else unit_plural
            details.append(f"*➤ {pending} {unit_p}* `new` ")
        if details:
            lines.append(f"{'\n'.join(details)}")

        return lines

    @staticmethod
    def _error_groups_section(
        error_groups: list,
        unit_plural: str,
        unit_singular: str,
        show: bool = True,
        max_groups: Optional[int] = None,
    ) -> list[str]:
        """Generate the error groups section lines."""
        if not show or not error_groups:
            return []

        groups = error_groups[:max_groups] if max_groups else error_groups
        lines = ["*Grupos de error:*"]
        for g in groups:
            desc  = g.get("description", "Sin descripción")
            count = g.get("count", 0)
            unit  = unit_singular if count == 1 else unit_plural
            lines.append(f"  • `{desc}` — {count} {unit}")
        return lines

    @staticmethod
    def _mentions_line(mention_user_ids: list[str]) -> Optional[str]:
        """Generate the mentions line."""
        if not mention_user_ids:
            return None
        mentions = " ".join(f"<@{uid}>" for uid in mention_user_ids)
        return f":luz_giratoia_movimiento: {mentions} favor de revisar a la brevedad de lo posible."

    @staticmethod
    def _freshdesk_line(freshdesk_url: Optional[str]) -> Optional[str]:
        """Generate the FreshDesk link line. Returns None when no URL is available."""
        if not freshdesk_url:
            return None
        return f"Tickets generados <{freshdesk_url}|FreshDesk>"


# ── Scenario builders ─────────────────────────────────────────────────────────

class HappyPathBuilder(_BaseMessageBuilder):
    """Build message for executions completed without errors (or with pending transactions)."""

    def build(self, ctx: MessageContext) -> str:
        total     = ctx.status.get("total_transactions", 0)
        completed = ctx.status.get("completed_transactions", total)
        failed    = ctx.status.get("failed_transactions", 0)
        pending   = max(0, total - completed - failed)

        unit_completed = ctx.transaction_unit if completed != 1 else ctx.transaction_unit_singular

        lines = [
            ctx.greeting,
            self._bot_header(ctx),
        ]

        if completed >= 1:
            lines.append(f"Se procesaron *{completed} {unit_completed}* correctamente. ✅")
        else:
            lines.append(f"Aún no se han procesado *{ctx.transaction_unit}*")

        if pending > 0:
            unit_p = ctx.transaction_unit_singular if pending == 1 else ctx.transaction_unit
            lines.append(f"*➤ {pending} {unit_p}* `new` ")

        lines.append("Sin errores reportados.")
        lines.append(self._timing_info(ctx.status))
        return "\n".join(lines)


class PartialFailureBuilder(_BaseMessageBuilder):
    """Build message for executions completed with failed transactions."""

    def build(self, ctx: MessageContext) -> str:
        status = ctx.status
        unit   = ctx.transaction_unit
        total  = status.get("total_transactions", 0)
        unit_label = ctx.transaction_unit_singular if total == 1 else unit

        lines = [
            ctx.greeting,
            self._bot_header(ctx),
            f"Se procesaron *{total} {unit_label}* con algunos errores. :warning:",
            "",
            *self._transaction_summary(status, unit, ctx.transaction_unit_singular),
            "",
            *self._error_groups_section(
                status.get("error_groups", []),
                unit,
                ctx.transaction_unit_singular,
                show=ctx.show_error_groups,
                max_groups=ctx.max_error_groups,
            ),
            "",
            self._timing_info(status),
        ]

        freshdesk = self._freshdesk_line(ctx.freshdesk_url)
        if freshdesk:
            lines.extend(["", freshdesk])

        return "\n".join(lines)


class CriticalFailureBuilder(_BaseMessageBuilder):
    """Build message for executions that fail completely (run_state = failed)."""

    def build(self, ctx: MessageContext) -> str:
        status = ctx.status
        unit   = ctx.transaction_unit

        lines = [
            ctx.greeting,
            self._bot_header(ctx),
            "La ejecución ha fallado de forma crítica. :warning-icon:",
            "Se requiere intervención inmediata.",
            "",
        ]

        mention = self._mentions_line(ctx.mention_user_ids)
        if mention:
            lines.append(mention)
            lines.append("")

        run_details = status.get("details")
        if run_details:
            lines.append("*Motivo del fallo:*")
            lines.append(f"```{run_details}```")
            lines.append("")

        error_section = self._error_groups_section(
            status.get("error_groups", []),
            unit,
            ctx.transaction_unit_singular,
            show=ctx.show_error_groups,
            max_groups=ctx.max_error_groups,
        )
        if error_section:
            lines.extend(error_section)
            lines.append("")

        lines.append(self._timing_info(status))

        freshdesk = self._freshdesk_line(ctx.freshdesk_url)
        if freshdesk:
            lines.extend(["", freshdesk])

        return "\n".join(lines)


class OvertimeBuilder(_BaseMessageBuilder):
    """Build message when overtime_flag = True."""

    def build(self, ctx: MessageContext) -> str:
        status  = ctx.status
        unit    = ctx.transaction_unit
        elapsed = status.get("elapsed_minutes")
        ref_avg = status.get("reference_avg_minutes")
        total   = status.get("total_transactions", 0)
        failed  = status.get("failed_transactions", 0)

        overtime_lines: list[str] = []
        if elapsed is not None and ref_avg is not None and ref_avg > 0:
            expected = ref_avg * total
            overage  = elapsed - expected
            overtime_lines = [
                f"Tiempo transcurrido: *{elapsed:.1f} min*",
                f"Tiempo esperado: *{expected:.1f} min*",
                f"Exceso: *{overage:.1f} min*",
            ]

        error_lines = self._error_groups_section(
            status.get("error_groups", []),
            unit,
            ctx.transaction_unit_singular,
            show=ctx.show_error_groups,
            max_groups=ctx.max_error_groups,
        )

        lines = [
            ctx.greeting,
            self._bot_header(ctx),
            "El bot ha superado su tiempo promedio de ejecución. :warning:",
            "",
            *overtime_lines,
            "",
            *self._transaction_summary(status, unit, ctx.transaction_unit_singular),
            "",
            *error_lines,
            *([""] if error_lines else []),
            self._timing_info(status),
        ]

        if failed > 0:
            freshdesk = self._freshdesk_line(ctx.freshdesk_url)
            if freshdesk:
                lines.extend(["", freshdesk])

        return "\n".join(lines)


class _InitialMessageBuilder(_BaseMessageBuilder):
    """Builder responsible for execution start notifications."""

    def build(self, ctx: MessageContext) -> str:
        # Incluir #run_id en el mensaje si está disponible en ctx.status
        run_id = ctx.status.get("run_id") if ctx.status else None
        run_id_tag = f" `#{run_id}`" if run_id else ""

        lines = [
            ctx.greeting,
            f"La ejecución{run_id_tag} del `{ctx.bot_id.upper()}` *→ {ctx.bot_name}* ha iniciado. :in_progress:",
        ]
        return "\n".join(lines)


# ── Registry y builder principal ──────────────────────────────────────────────

_BUILDER_REGISTRY: dict[ExecutionScenario, _BaseMessageBuilder] = {
    ExecutionScenario.HAPPY_PATH:       HappyPathBuilder(),
    ExecutionScenario.PARTIAL_FAILURE:  PartialFailureBuilder(),
    ExecutionScenario.CRITICAL_FAILURE: CriticalFailureBuilder(),
    ExecutionScenario.OVERTIME:         OvertimeBuilder(),
}

_INITIAL_BUILDER  = _InitialMessageBuilder()


class RPAMessageBuilder:
    """
    Main facade of the module.

    Coordinates scenario resolution, builder selection and final message generation.

    Main methods:
        build()         → Execution status message.
        build_initial() → Execution start notification (acepta run_id opcional).
    """

    def __init__(
        self,
        resolver: Optional[ScenarioResolver] = None,
        greeting_provider: Optional[GreetingProvider] = None,
        builder_registry: Optional[dict[ExecutionScenario, _BaseMessageBuilder]] = None,
    ) -> None:
        self._resolver  = resolver          or ScenarioResolver()
        self._greetings = greeting_provider or GreetingProvider()
        self._registry  = builder_registry  or _BUILDER_REGISTRY

    def build(
        self,
        bot_id: str,
        bot_name: str,
        status_dict: dict,
        transaction_unit: str = "transacciones",
        transaction_unit_singular: str = "transacción",
        show_error_groups: bool = True,
        max_error_groups: Optional[int] = None,
        mention_user_ids: Optional[List[str]] = None,
        freshdesk_url: Optional[str] = None,
    ) -> str:
        """
        Build the Slack message representing the current RPA execution state.
        Used by bee_informa (single run_id, no run_id in header).

        The execution scenario (HAPPY_PATH, PARTIAL_FAILURE, CRITICAL_FAILURE,
        OVERTIME) is resolved automatically from the provided status_dict.

        Returns:
            Slack mrkdwn formatted message.
        """
        scenario = self._resolver.resolve(status_dict)
        builder  = self._registry[scenario]

        ctx = MessageContext(
            status=status_dict,
            bot_id=bot_id,
            bot_name=bot_name,
            transaction_unit=transaction_unit,
            transaction_unit_singular=transaction_unit_singular,
            greeting=self._greetings.get(),
            show_error_groups=show_error_groups,
            max_error_groups=max_error_groups,
            mention_user_ids=mention_user_ids or [],
            freshdesk_url=freshdesk_url,
        )

        return builder.build(ctx)

    def build_multi(
        self,
        bot_id: str,
        bot_name: str,
        status_list: list[dict],
        transaction_unit: str = "transacciones",
        transaction_unit_singular: str = "transacción",
        show_error_groups: bool = True,
        max_error_groups: Optional[int] = None,
        mention_user_ids: Optional[List[str]] = None,
        freshdesk_url: Optional[str] = None,
    ) -> str:
        """
        Build a fused message containing multiple execution status blocks.

        The first block includes a greeting. Subsequent blocks omit the greeting
        to avoid repeated salutations in the same message.
        """
        if not status_list:
            raise ValueError("status_list cannot be empty for build_multi().")

        blocks: list[str] = []
        greeting = self._greetings.get()
        mentions = mention_user_ids or []

        for index, status_dict in enumerate(status_list):
            scenario = self._resolver.resolve(status_dict)
            builder = self._registry[scenario]

            ctx = MessageContext(
                status=status_dict,
                bot_id=bot_id,
                bot_name=bot_name,
                transaction_unit=transaction_unit,
                transaction_unit_singular=transaction_unit_singular,
                greeting=greeting if index == 0 else "",
                show_error_groups=show_error_groups,
                max_error_groups=max_error_groups,
                mention_user_ids=mentions,
                freshdesk_url=freshdesk_url,
            )
            blocks.append(builder.build(ctx))

        return "\n\n".join(blocks)

    def build_initial(
        self,
        bot_id: str,
        bot_name: str,
        run_id: str | None = None,
    ) -> str:
        """
        Build the execution start message, including the #run_id.

        This method does not require a status_dict and bypasses the
        ScenarioResolver because it is triggered when an execution begins.

        Args:
            bot_id:   Bot identifier (e.g. 'AIN.002').
            bot_name: Human-readable bot name.
            run_id:   Execution run ID to show in the message (e.g. "165685"). Optional.
        """
        ctx = MessageContext(
            status={"run_id": run_id} if run_id else {},
            bot_id=bot_id,
            bot_name=bot_name,
            transaction_unit="",
            transaction_unit_singular="",
            greeting=self._greetings.get(),
            run_id=run_id,
        )
        return _INITIAL_BUILDER.build(ctx)

    def build_for_scenario(
        self,
        scenario: ExecutionScenario,
        status_dict: dict,
        bot_id: str,
        bot_name: str,
        transaction_unit: str = "transacciones",
        transaction_unit_singular: str = "transacción",
        show_error_groups: bool = True,
        max_error_groups: Optional[int] = None,
        mention_user_ids: Optional[List[str]] = None,
        freshdesk_url: Optional[str] = None,
    ) -> str:
        """
        Build a message forcing a specific execution scenario.
        Primarily used for testing and debugging message generation.
        """
        builder = self._registry[scenario]
        ctx = MessageContext(
            status=status_dict,
            bot_id=bot_id,
            bot_name=bot_name,
            transaction_unit=transaction_unit,
            transaction_unit_singular=transaction_unit_singular,
            greeting=self._greetings.get(),
            show_error_groups=show_error_groups,
            max_error_groups=max_error_groups,
            mention_user_ids=mention_user_ids or [],
            freshdesk_url=freshdesk_url,
        )
        return builder.build(ctx)