"""Agent Monitoring

Revision ID: 0aeeff0865f1
Revises: b0059b66b5d6
Create Date: 2026-05-11 16:10:58.007367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aeeff0865f1'
down_revision: Union[str, None] = 'b0059b66b5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_monitoring',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('beecker_id', sa.String(length=10), nullable=False),
    sa.Column('platform_id', sa.String(length=10), nullable=False),
    sa.Column('platform', sa.Enum('cloud', 'hub', name='platformtype'), nullable=False),
    sa.Column('transaction_unit', sa.String(length=50), nullable=False),
    sa.Column('manage_flags', sa.JSON(), nullable=False),
    sa.Column('roc_agents', sa.JSON(), nullable=True),
    sa.Column('SLA_time', sa.Integer(), nullable=False),
    sa.Column('transactions_exceeded_sla', sa.JSON(), nullable=True),
    sa.Column('error_status', sa.JSON(), nullable=True),
    sa.Column('transactions_with_errors', sa.JSON(), nullable=True),
    sa.Column('completed_status', sa.JSON(), nullable=True),
    sa.Column('cut_off_time', sa.Time(), nullable=False),
    sa.Column('slack_message_id', sa.String(length=100), nullable=True),
    sa.Column('slack_channel_id', sa.String(length=100), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_monitoring')
    # ### end Alembic commands ###
