"""Normalización - Jobs

Revision ID: 3bee9ea20e54
Revises: 68e141a01c86
Create Date: 2026-03-10 09:40:08.993385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3bee9ea20e54'
down_revision: Union[str, None] = '68e141a01c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_client', 'id_scheduler_job',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=191),
               existing_nullable=True)
    op.create_foreign_key(None, 'agent_client', 'jobs', ['id_scheduler_job'], ['id'])
    op.alter_column('rpa_dashboard_client', 'id_scheduler_job',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=191),
               existing_nullable=True)
    op.create_foreign_key(None, 'rpa_dashboard_client', 'jobs', ['id_scheduler_job'], ['id'])
    op.alter_column('rpa_uipath_client', 'id_scheduler_job',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=191),
               existing_nullable=True)
    op.create_foreign_key(None, 'rpa_uipath_client', 'jobs', ['id_scheduler_job'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rpa_uipath_client', type_='foreignkey')
    op.alter_column('rpa_uipath_client', 'id_scheduler_job',
               existing_type=sa.String(length=191),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'rpa_dashboard_client', type_='foreignkey')
    op.alter_column('rpa_dashboard_client', 'id_scheduler_job',
               existing_type=sa.String(length=191),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'agent_client', type_='foreignkey')
    op.alter_column('agent_client', 'id_scheduler_job',
               existing_type=sa.String(length=191),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
