"""initial

Revision ID: 68e141a01c86
Revises: 
Create Date: 2026-03-09 22:28:21.016758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e141a01c86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('id_agent', sa.String(length=100), nullable=False),
    sa.Column('id_beecker', sa.String(length=100), nullable=False),
    sa.Column('process_name', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.Enum('cloud', 'hub', name='platformtype'), nullable=False),
    sa.PrimaryKeyConstraint('id_agent')
    )
    op.create_table('client',
    sa.Column('id_client', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id_client')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_path', sa.String(length=500), nullable=False),
    sa.Column('trigger_type', sa.Enum('cron', 'interval', 'date', name='triggertype'), nullable=False),
    sa.Column('trigger_args', sa.JSON(), nullable=False),
    sa.Column('job_kwargs', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', 'error', name='jobstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_run_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpa_dashboard',
    sa.Column('id_rpa', sa.String(length=100), nullable=False),
    sa.Column('id_beecker', sa.String(length=100), nullable=False),
    sa.Column('process_name', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.Enum('cloud', 'hub', name='platformtype'), nullable=False),
    sa.PrimaryKeyConstraint('id_rpa')
    )
    op.create_table('rpa_uipath',
    sa.Column('id_rpa', sa.String(length=100), nullable=False),
    sa.Column('id_beecker', sa.String(length=100), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=False),
    sa.Column('robot_name', sa.String(length=200), nullable=False),
    sa.Column('process_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_rpa')
    )
    op.create_table('agent_client',
    sa.Column('id_agent', sa.String(length=100), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('monitor_type', sa.Enum('bee_observa', 'bee_informa', 'bee_comunica', name='monitortype'), nullable=False),
    sa.Column('transaction_unit', sa.String(length=100), nullable=False),
    sa.Column('slack_channel', sa.String(length=100), nullable=True),
    sa.Column('manage_flags', sa.JSON(), nullable=True),
    sa.Column('roc_agents', sa.JSON(), nullable=True),
    sa.Column('id_scheduler_job', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_agent'], ['agent.id_agent'], ),
    sa.ForeignKeyConstraint(['id_client'], ['client.id_client'], ),
    sa.PrimaryKeyConstraint('id_agent', 'id_client')
    )
    op.create_table('agent_state_error',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_agent', sa.String(length=100), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_agent'], ['agent.id_agent'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=191), nullable=False),
    sa.Column('status', sa.Enum('success', 'failure', 'running', name='executionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpa_dashboard_business_error',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rpa', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['id_rpa'], ['rpa_dashboard.id_rpa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpa_dashboard_client',
    sa.Column('id_rpa', sa.String(length=100), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('monitor_type', sa.Enum('bee_observa', 'bee_informa', 'bee_comunica', name='monitortype'), nullable=False),
    sa.Column('transaction_unit', sa.String(length=100), nullable=False),
    sa.Column('slack_channel', sa.String(length=100), nullable=True),
    sa.Column('manage_flags', sa.JSON(), nullable=True),
    sa.Column('roc_agents', sa.JSON(), nullable=True),
    sa.Column('id_scheduler_job', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['client.id_client'], ),
    sa.ForeignKeyConstraint(['id_rpa'], ['rpa_dashboard.id_rpa'], ),
    sa.PrimaryKeyConstraint('id_rpa', 'id_client')
    )
    op.create_table('rpa_uipath_business_error',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_rpa', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['id_rpa'], ['rpa_uipath.id_rpa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpa_uipath_client',
    sa.Column('id_rpa', sa.String(length=100), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('monitor_type', sa.Enum('bee_observa', 'bee_informa', 'bee_comunica', name='monitortype'), nullable=False),
    sa.Column('transaction_unit', sa.String(length=100), nullable=False),
    sa.Column('slack_channel', sa.String(length=100), nullable=True),
    sa.Column('manage_flags', sa.JSON(), nullable=True),
    sa.Column('roc_agents', sa.JSON(), nullable=True),
    sa.Column('id_scheduler_job', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['client.id_client'], ),
    sa.ForeignKeyConstraint(['id_rpa'], ['rpa_uipath.id_rpa'], ),
    sa.PrimaryKeyConstraint('id_rpa', 'id_client')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rpa_uipath_client')
    op.drop_table('rpa_uipath_business_error')
    op.drop_table('rpa_dashboard_client')
    op.drop_table('rpa_dashboard_business_error')
    op.drop_table('job_executions')
    op.drop_table('agent_state_error')
    op.drop_table('agent_client')
    op.drop_table('rpa_uipath')
    op.drop_table('rpa_dashboard')
    op.drop_table('jobs')
    op.drop_table('client')
    op.drop_table('agent')
    # ### end Alembic commands ###
