"""initial

Revision ID: 763027ab725d
Revises: 
Create Date: 2026-03-19 16:14:39.581917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763027ab725d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('client_name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=191), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_path', sa.String(length=500), nullable=False),
    sa.Column('trigger_type', sa.Enum('cron', 'interval', 'date', name='triggertype'), nullable=False),
    sa.Column('trigger_args', sa.JSON(), nullable=False),
    sa.Column('job_kwargs', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', 'error', name='jobstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_run_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=191), nullable=False),
    sa.Column('status', sa.Enum('success', 'failure', 'running', name='executionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpa_dashboard',
    sa.Column('id_beecker', sa.String(length=10), nullable=False),
    sa.Column('id_dashboard', sa.String(length=40), nullable=False),
    sa.Column('process_name', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.Enum('cloud', 'hub', name='platformtype'), nullable=False),
    sa.Column('business_errors', sa.JSON(), nullable=True),
    sa.Column('id_client', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id_beecker')
    )
    op.create_table('rpa_uipath',
    sa.Column('uipath_robot_name', sa.String(length=200), nullable=False),
    sa.Column('id_beecker', sa.String(length=100), nullable=False),
    sa.Column('beecker_name', sa.String(length=200), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=False),
    sa.Column('business_errors', sa.JSON(), nullable=True),
    sa.Column('id_client', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['client.id'], ),
    sa.PrimaryKeyConstraint('uipath_robot_name')
    )
    op.create_table('rpa_dashboard_monitoring',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('id_beecker', sa.String(length=10), nullable=False),
    sa.Column('monitor_type', sa.Enum('bee_observa', 'bee_informa', 'bee_comunica', name='monitortype'), nullable=False),
    sa.Column('transaction_unit', sa.String(length=100), nullable=False),
    sa.Column('slack_channel', sa.String(length=100), nullable=False),
    sa.Column('manage_flags', sa.JSON(), nullable=False),
    sa.Column('roc_agents', sa.JSON(), nullable=True),
    sa.Column('id_scheduler_job', sa.String(length=191), nullable=True),
    sa.ForeignKeyConstraint(['id_beecker'], ['rpa_dashboard.id_beecker'], ),
    sa.ForeignKeyConstraint(['id_scheduler_job'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpa_uipath_monitoring',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('uipath_robot_name', sa.String(length=200), nullable=False),
    sa.Column('monitor_type', sa.Enum('bee_observa', 'bee_informa', 'bee_comunica', name='monitortype'), nullable=False),
    sa.Column('transaction_unit', sa.String(length=100), nullable=False),
    sa.Column('slack_channel', sa.String(length=100), nullable=False),
    sa.Column('manage_flags', sa.JSON(), nullable=True),
    sa.Column('roc_agents', sa.JSON(), nullable=True),
    sa.Column('id_scheduler_job', sa.String(length=191), nullable=True),
    sa.ForeignKeyConstraint(['id_scheduler_job'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['uipath_robot_name'], ['rpa_uipath.uipath_robot_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rpa_uipath_monitoring')
    op.drop_table('rpa_dashboard_monitoring')
    op.drop_table('rpa_uipath')
    op.drop_table('rpa_dashboard')
    op.drop_table('job_executions')
    op.drop_table('jobs')
    op.drop_table('client')
    # ### end Alembic commands ###
