"""Group by column added

Revision ID: b0059b66b5d6
Revises: 083ea172675e
Create Date: 2026-04-22 15:09:19.950185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0059b66b5d6'
down_revision: Union[str, None] = '083ea172675e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rpa_dashboard', sa.Column('group_by_column', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rpa_dashboard', 'group_by_column')
    # ### end Alembic commands ###
