"""Freshdesk ID & Beecker Client ID Added

Revision ID: fd14443e67ea
Revises: 80a0d841dc7a
Create Date: 2026-03-30 06:55:02.237557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd14443e67ea'
down_revision: Union[str, None] = '80a0d841dc7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('id_beecker', sa.String(length=4), nullable=False))
    op.create_unique_constraint(None, 'client', ['id_freshdesk'])
    op.create_unique_constraint(None, 'client', ['id_beecker'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_column('client', 'id_beecker')
    # ### end Alembic commands ###
